apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: ecommerce
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      
    scrape_configs:
      - job_name: 'ecom-core-api'
        static_configs:
          - targets: ['ecom-core-service:80']
        metrics_path: '/metrics'
        scrape_interval: 30s
        
      - job_name: 'ecom-users-api'
        static_configs:
          - targets: ['ecom-users-service:80']
        metrics_path: '/metrics'
        scrape_interval: 30s
        
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
        - role: pod
          namespaces:
            names:
            - ecommerce
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: kubernetes_pod_name
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-external-config
  namespace: ecommerce
data:
  kubernetes-scrape-config.yml: |
    # Add this to your existing Prometheus configuration on self-hosted runner
    scrape_configs:
      - job_name: 'ecom-core-api-k8s'
        kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names:
            - ecommerce
        relabel_configs:
        - source_labels: [__meta_kubernetes_service_name]
          action: keep
          regex: ecom-core-service
        - source_labels: [__meta_kubernetes_endpoint_port_name]
          action: keep
          regex: http
        - target_label: __address__
          replacement: minikube_ip:service_port
        
      - job_name: 'ecom-users-api-k8s'
        kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names:
            - ecommerce
        relabel_configs:
        - source_labels: [__meta_kubernetes_service_name]
          action: keep
          regex: ecom-users-service
        - source_labels: [__meta_kubernetes_endpoint_port_name]
          action: keep
          regex: http
        - target_label: __address__
          replacement: minikube_ip:service_port
---
apiVersion: v1
kind: Service
metadata:
  name: external-prometheus-access
  namespace: ecommerce
  labels:
    app: external-monitoring
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30301
    name: core-metrics
  selector:
    app: ecom-core-api
---
apiVersion: v1
kind: Service
metadata:
  name: external-prometheus-access-users
  namespace: ecommerce
  labels:
    app: external-monitoring
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30302
    name: users-metrics
  selector:
    app: ecom-users-api