apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ecommerce-monitor
  namespace: ecommerce
  labels:
    app: ecommerce
spec:
  selector:
    matchLabels:
      app: ecommerce
  endpoints:
  - port: http
    path: /metrics
    interval: 15s