services:
  ecom.gateway.api:
    image: ${DOCKER_REGISTRY-}ecomgatewayapi
    build:
      context: .
      dockerfile: Ecom.Gateway/src/Ecom.Gateway.API/Dockerfile
    ports:
      - "5300:8080"
    depends_on:
      - ecom.core.api
      - ecom.users.api
    networks:
      - ecommerce-network
    restart: unless-stopped

  ecom.core.api:
    image: ${DOCKER_REGISTRY-}ecomcoreapi
    build:
      context: .
      dockerfile: Ecom.Core/src/Ecom.Core.API/Dockerfile
    ports:
      - "5301:8080"
    networks:
      - ecommerce-network
    restart: unless-stopped
   

  ecom.users.api:
    image: ${DOCKER_REGISTRY-}ecomusersapi
    build:
      context: .
      dockerfile: Ecom.Users/src/Ecom.Users.API/Dockerfile
    ports:
      - "5302:8080"
    networks:
      - ecommerce-network
    restart: unless-stopped

networks:
  ecommerce-network:
    driver: bridge
