version: '3.8'

services:
  ecom.aspire:
    build:
      context: .
      dockerfile: Moclaw.Ecommerce.AppHost/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  ecom.users.api:
    build:
      context: .
      dockerfile: Moclaw.Ecommerce.Users/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  ecomcore.api:
    build:
      context: .
      dockerfile: Moclaw.Ecommerce.Core/Dockerfile
    ports:
      - "5002:5002"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

