version: '3.8'

services:
  ecom.core.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_LOGGING__LOGLEVEL__DEFAULT=Warning
      - ASPNETCORE_LOGGING__LOGLEVEL__MICROSOFT=Warning
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  ecom.users.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_LOGGING__LOGLEVEL__DEFAULT=Warning
      - ASPNETCORE_LOGGING__LOGLEVEL__MICROSOFT=Warning
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  prometheus:
    volumes:
      - /etc/localtime:/etc/localtime:ro
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  grafana:
    volumes:
      - /etc/localtime:/etc/localtime:ro
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
