version: '3.8'

services:
  ecom.users.api:
    container_name: ecom-users-api
    build:
      context: .
      dockerfile: Moclaw.Ecommerce.Users.API/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001

  ecomcore.api:
    container_name: ecom-core-api
    build:
      context: .
      dockerfile: Moclaw.Ecommerce.Core.API/Dockerfile
    ports:
      - "5002:5002"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5002

