global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'ecommerce-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ecom-core-api'
    static_configs:
      - targets: ['ecom.core.api:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'ecom-users-api'
    static_configs:
      - targets: ['ecom.users.api:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s
