apiVersion: v1
kind: ConfigMap
metadata:
  name: core-api-config
  namespace: ecommerce
data:
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*"
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: users-api-config
  namespace: ecommerce
data:
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*",
      "JwtOptions": {
        "Issuer": "ecom-users-api",
        "Audience": "ecom-clients",
        "ExpiryMinutes": 60
      }
    }
