apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-core-api
  namespace: ecommerce
  labels:
    app: ecom-core-api
    service: core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecom-core-api
  template:
    metadata:
      labels:
        app: ecom-core-api
        service: core
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: ecom-core-api
        image: moclaw/ecom-core-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        - name: ElasticApm__Enabled
          value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: ecom-core-service
  namespace: ecommerce
  labels:
    app: ecom-core-api
spec:
  selector:
    app: ecom-core-api
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  type: ClusterIP
