apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-config
  namespace: ecommerce
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'ecom-core-api'
        static_configs:
          - targets: ['ecom-core-service:80']
        metrics_path: /metrics
      - job_name: 'ecom-users-api'
        static_configs:
          - targets: ['ecom-users-service:80']
        metrics_path: /metrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus
      volumes:
      - name: config
        configMap:
          name: monitoring-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: ecommerce
spec:
  selector:
    app: prometheus
  ports:
  - port: 9090
    targetPort: 9090
  type: NodePort
