apiVersion: v1
kind: Namespace
metadata:
  name: ecommerce
  labels:
    name: ecommerce
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: node-labels
  namespace: ecommerce
data:
  core-node: "minikube-core"
  users-node: "minikube-users"
