apiVersion: v1
kind: Secret
metadata:
  name: core-api-secrets
  namespace: ecommerce
type: Opaque
stringData:
  connection-string: "Host=postgres-service;Port=5432;Database=EcomCore;Username=postgres;Password=postgres123"
---
apiVersion: v1
kind: Secret
metadata:
  name: users-api-secrets
  namespace: ecommerce
type: Opaque
stringData:
  connection-string: "Host=postgres-service;Port=5432;Database=EcomUsers;Username=postgres;Password=postgres123"
  jwt-secret: "your-very-secure-jwt-secret-key-here-should-be-at-least-256-bits"
