apiVersion: v1
kind: PersistentVolume
metadata:
  name: ecom-shared-pv
  namespace: ecommerce
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: shared-storage
  hostPath:
    path: /data/ecommerce-shared
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ecom-shared-pvc
  namespace: ecommerce
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: shared-storage
---
apiVersion: v1
kind: Secret
metadata:
  name: ecom-secrets
  namespace: ecommerce
type: Opaque
data:
  database-connection: ZGF0YWJhc2VfY29ubmVjdGlvbl9zdHJpbmc= # base64 encoded
  jwt-secret: and0X3NlY3JldF9rZXk= # base64 encoded
  api-key: YXBpX2tleV92YWx1ZQ== # base64 encoded
