apiVersion: v1
kind: Service
metadata:
  name: ecom-core-service
  namespace: ecommerce
  labels:
    app: ecom-core-api
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
    nodePort: 30003
  - port: 443
    targetPort: 8081
    protocol: TCP
    name: https
    nodePort: 30004
  selector:
    app: ecom-core-api
