name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_REGISTRY: localhost:5000
  KUBECTL_VERSION: v1.28.0

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Start Minikube
      uses: medyagh/setup-minikube@master
      with:
        minikube-version: 1.32.0
        kubernetes-version: v1.28.0
        driver: docker
        addons: registry

    - name: Build Docker Images
      run: |
        eval $(minikube docker-env)
        
        # Build Users API
        docker build -t ecom-users-api:latest -f Ecom.Users/src/Ecom.Users.API/Dockerfile .
        
        # Build Core API  
        docker build -t ecom-core-api:latest -f Ecom.Core/src/Ecom.Core.API/Dockerfile .

    - name: Apply Kubernetes Manifests
      run: |
        kubectl apply -f k8s/namespace.yml
        kubectl apply -f k8s/users-service/
        kubectl apply -f k8s/core-service/
        
    - name: Wait for Deployments
      run: |
        kubectl wait --for=condition=available --timeout=300s deployment/ecom-users-api -n ecommerce
        kubectl wait --for=condition=available --timeout=300s deployment/ecom-core-api -n ecommerce
        
    - name: Get Service URLs
      run: |
        minikube service ecom-users-service --url -n ecommerce
        minikube service ecom-core-service --url -n ecommerce
