apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-core-api
  namespace: ecommerce
  labels:
    app: ecom-core-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecom-core-api
  template:
    metadata:
      labels:
        app: ecom-core-api
    spec:
      nodeSelector:
        service: core
      containers:
      - name: ecom-core-api
        image: ecom-core-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8081
          name: https
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ASPNETCORE_HTTP_PORTS
          value: "8080"
        - name: ASPNETCORE_HTTPS_PORTS
          value: "8081"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
