apiVersion: v1
kind: Service
metadata:
  name: users-api-service
  namespace: ecommerce
  labels:
    app: users-api
spec:
  type: NodePort
  ports:
  - port: 5302
    targetPort: 8080
    nodePort: 30302
    protocol: TCP
    name: http
  selector:
    app: users-api
---
apiVersion: v1
kind: Service
metadata:
  name: users-api-service-internal
  namespace: ecommerce
  labels:
    app: users-api
spec:
  type: ClusterIP
  ports:
  - port: 5302
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: users-api
