apiVersion: v1
kind: Service
metadata:
  name: core-api-service
  namespace: ecommerce
  labels:
    app: core-api
spec:
  type: NodePort
  ports:
  - port: 5301
    targetPort: 8080
    nodePort: 30301
    protocol: TCP
    name: http
  selector:
    app: core-api
---
apiVersion: v1
kind: Service
metadata:
  name: core-api-service-internal
  namespace: ecommerce
  labels:
    app: core-api
spec:
  type: ClusterIP
  ports:
  - port: 5301
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: core-api
